# Generated by Django 3.2.5 on 2021-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
