# Generated by Django 3.2.5 on 2021-07-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210729_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.articles', verbose_name='Статья'),
        ),
    ]
