# Generated by Django 3.2.5 on 2021-07-29 18:52

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='comments.comments', verbose_name='Родитель'),
        ),
    ]
